# Definição do Grupo guesses
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guesses
  description: Grupo de usuários convidados
spec:
  type: team
  profile:
    displayName: Guests Group
    email: guests-group@example.com
  children:
    - guest  # Adiciona o usuário guest como membro do grupo guesses

---

# Definição do Usuário guest
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  profile:
    displayName: Guest User
    email: guest.user@example.com
  memberOf:
    - guesses  # Define que o usuário guest é membro do grupo guesses

---

# Definição do Template para criação de novos serviços
apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: example-service-template
  title: Example Service Template
  description: Template para criar um novo serviço backend com Spring Boot
  tags:
    - java
    - springboot
    - microservices
spec:
  owner: guesses  # Define o grupo guesses como o proprietário do template
  type: service
  path: ./template.yaml  # Caminho para o arquivo do template
  templater: cookiecutter
  schema:
    required:
      - name
    properties:
      name:
        title: Nome do Serviço
        type: string
