apiVersion: backstage.io/v1alpha1
kind: Template
metadata:
  name: my-template
spec:
  owner: team/devops
  type: service
  parameters:
    - title: Projeto BRQ - POC voltada ao uso de Backstage
      properties:
        name:
          title: BRQ_Backstage
          type: string
        description:
          title: POC com objetivo de estruturar uma POC usando os serviços de Backstage.
          type: string
  steps:
    - id: fetch-base
      name: Buscar Template Base
      action: fetch:template
      input:
        url: 'https://github.com/eduardojnet/backstage-template'
        targetPath: './{{ parameters.name }}'
    - id: publish
      name: Publicar no GitHub
      action: publish:github
      input:
        repoUrl: 'https://github.com/{{ parameters.name }}'
        description: '{{ parameters.description }}'
